baseURL = "https://deybhayden.me/"
languageCode = "en-us"
title = "Software Engineer"
theme = "anatole"
summarylength = 10
enableEmoji = true

# Google Analytics
googleAnalytics = "UA-167363974-1"

[params]
title = "Ben Hayden"
author = "Ben Hayden"
description = "👋 Hey, what's up?"
profilePicture = "images/profile.jpg"
keywords = "ben hayden, software engineer, engineer manager"
mainSections = ["post"]

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/benhayden/"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/deybhayden/"

[[params.socialIcons]]
icon = "fa-twitter"
title = "Twitter"
url = "https://www.twitter.com/deybhayden"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:contact@deybhayden.me"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"
